#!/usr/bin/env python2.7

import json
import argparse
import os
import sys

import common

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--count', default=3,
        help='number of memcache nodes')
    args = parser.parse_args()

    root = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '..'))

    for node in common.LoadNodes():
        node.stop()

    names = ['memcache-{0:04d}'.format(i) for i in range(args.count)]
    nodes = [common.LoadNode(common.StartMemcached(name)) for name in names]

    with open(os.path.join(root, 'pub/config.php'), 'w') as w:
        ips = {node.name():node.ip_address() for node in nodes}
        w.write('<?php\n')
        w.write('return json_decode(\'{}\', true);\n'.format(json.dumps(ips)))

    common.StartApp('app', root)

if __name__ == '__main__':
    sys.exit(main())